#! /bin/sh

echo $HOSTNAME | grep bender.engr.ucr.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 26215 
else 
rsh bender.engr.ucr.edu kill 26215 
 sleep 10 
rsh bender.engr.ucr.edu kill -9 26215 
fi
