#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /home/cemaj/tarora/eecs168/pvjob_mylibrary.ripple_carry_adder_4bit.icv.lvs/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /home/cemaj/tarora/eecs168/pvjob_mylibrary.ripple_carry_adder_4bit.icv.lvs/./TOPCELLNAME_err | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /home/cemaj/tarora/eecs168/pvjob_mylibrary.ripple_carry_adder_4bit.icv.lvs/ripple_carry_adder_4bit.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /home/cemaj/tarora/eecs168/pvjob_mylibrary.ripple_carry_adder_4bit.icv.lvs/run_details/duse_master.tmp && \
mv /home/cemaj/tarora/eecs168/pvjob_mylibrary.ripple_carry_adder_4bit.icv.lvs/run_details/duse_master.tmp /home/cemaj/tarora/eecs168/pvjob_mylibrary.ripple_carry_adder_4bit.icv.lvs/run_details/duse_master
