#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /home/cemaj/tarora/eecs168/pvjob_mylibrary.adder_1bit.icv.drc/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /home/cemaj/tarora/eecs168/pvjob_mylibrary.adder_1bit.icv.drc/adder_1bit.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /home/cemaj/tarora/eecs168/pvjob_mylibrary.adder_1bit.icv.drc/run_details/duse_master.tmp && \
mv /home/cemaj/tarora/eecs168/pvjob_mylibrary.adder_1bit.icv.drc/run_details/duse_master.tmp /home/cemaj/tarora/eecs168/pvjob_mylibrary.adder_1bit.icv.drc/run_details/duse_master
