#! /bin/sh

echo $HOSTNAME | grep bender.engr.ucr.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 15090 
else 
rsh bender.engr.ucr.edu kill 15090 
 sleep 10 
rsh bender.engr.ucr.edu kill -9 15090 
fi
