//
// Milkyway Hierarchical Verilog Dump:
// Generated on 03/13/2019 at 11:16:52
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :Fa_4bit_icc
// Cell Name    :gcdGCDUnit_rtl
// Hierarchy delimiter:'/'
// Write Command : write_verilog gcdGCDUnit_rtl.output.v
//


module gcdGCDUnit_rtl (operands_bits_A , operands_bits_B , 
    result_bits_data , result_val , operands_rdy , result_rdy , 
    operands_val , reset , clk );
input  [15:0] operands_bits_A ;
input  [15:0] operands_bits_B ;
output [15:0] result_bits_data ;
output result_val ;
output operands_rdy ;
input  result_rdy ;
input  operands_val ;
input  reset ;
input  clk ;


wire [15:0] GCDdpath0_B_reg ;
wire [1:0] GCDctrl0_state ;

AOINVX1 U240 (.IN ( n395 ) , .QN ( n139 ) ) ;
NOR2X1 U214 (.QN ( n331 ) , .IN1 ( result_bits_data[11] ) , .IN2 ( n383 ) ) ;
NOR2X0 U265 (.QN ( n228 ) , .IN1 ( result_bits_data[8] ) , .IN2 ( n368 ) ) ;
NAND2X0 U139 (.IN1 ( n157 ) , .IN2 ( n219 ) , .QN ( n340 ) ) ;
NOR2X1 U270 (.IN2 ( n160 ) , .QN ( n180 ) , .IN1 ( n161 ) ) ;
INVX1 U9 (.IN ( n61 ) , .QN ( result_bits_data[2] ) ) ;
NAND3X0 U100 (.QN ( n115 ) , .IN3 ( n415 ) , .IN2 ( n414 ) , .IN1 ( n413 ) ) ;
NAND2X0 U99 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[1] ) , .QN ( n415 ) ) ;
NAND2X0 U96 (.IN1 ( n362 ) , .IN2 ( result_bits_data[1] ) , .QN ( n414 ) ) ;
NAND2X0 U83 (.IN1 ( GCDdpath0_B_reg[1] ) , .IN2 ( n410 ) , .QN ( n413 ) ) ;
NOR2X2 U71 (.IN2 ( n231 ) , .QN ( n412 ) , .IN1 ( n162 ) ) ;
NAND2X0 U289 (.IN2 ( n177 ) , .IN1 ( n178 ) , .QN ( n179 ) ) ;
INVX1 U73 (.IN ( n121 ) , .QN ( n361 ) ) ;
NOR2X0 U175 (.QN ( n229 ) , .IN1 ( GCDdpath0_B_reg[8] ) , .IN2 ( n369 ) ) ;
NOR2X0 U370 (.QN ( n330 ) , .IN1 ( n325 ) , .IN2 ( n326 ) ) ;
NAND2X2 U252 (.IN2 ( n148 ) , .IN1 ( n149 ) , .QN ( n314 ) ) ;
AOINVX2 U273 (.IN ( n412 ) , .QN ( n165 ) ) ;
AOINVX2 U271 (.IN ( n229 ) , .QN ( n305 ) ) ;
NAND2X1 U245 (.IN2 ( result_bits_data[2] ) , .IN1 ( n390 ) , .QN ( n259 ) ) ;
NOR2X1 U171 (.QN ( n326 ) , .IN1 ( n76 ) , .IN2 ( n389 ) ) ;
NOR2X1 U212 (.QN ( n162 ) , .IN1 ( n305 ) , .IN2 ( n230 ) ) ;
DFFX2 GCDctrl0_state_reg_0_ (.CLK ( clk ) , .QN ( n367 ) 
    , .Q ( GCDctrl0_state[0] ) , .D ( n118 ) ) ;
DFFX2 GCDctrl0_state_reg_1_ (.CLK ( clk ) , .QN ( n366 ) 
    , .Q ( GCDctrl0_state[1] ) , .D ( n119 ) ) ;
NOR2X0 U246 (.QN ( n142 ) , .IN1 ( n259 ) , .IN2 ( n285 ) ) ;
AOINVX1 U251 (.IN ( n294 ) , .QN ( n183 ) ) ;
AOINVX1 U243 (.IN ( n285 ) , .QN ( n141 ) ) ;
AOINVX1 U250 (.IN ( n147 ) , .QN ( n297 ) ) ;
NOR2X0 U143 (.IN1 ( n284 ) , .IN2 ( n142 ) , .QN ( n143 ) ) ;
AOINVX1 U264 (.IN ( n326 ) , .QN ( n209 ) ) ;
AOINVX1 U263 (.IN ( n331 ) , .QN ( n158 ) ) ;
AOINVX1 U276 (.IN ( n329 ) , .QN ( n208 ) ) ;
AOINVX1 U262 (.IN ( n241 ) , .QN ( n219 ) ) ;
AOINVX1 U260 (.IN ( n346 ) , .QN ( n341 ) ) ;
AOINVX1 U261 (.IN ( n242 ) , .QN ( n157 ) ) ;
AOINVX1 U267 (.IN ( n207 ) , .QN ( n159 ) ) ;
AOINVX1 U16 (.IN ( n83 ) , .QN ( n47 ) ) ;
AOINVX1 U288 (.IN ( n352 ) , .QN ( n173 ) ) ;
NAND2X0 U269 (.IN2 ( n217 ) , .IN1 ( n169 ) , .QN ( n160 ) ) ;
AOINVX1 U299 (.IN ( n195 ) , .QN ( n317 ) ) ;
AOINVX1 U239 (.IN ( n388 ) , .QN ( n138 ) ) ;
INVX1 U314 (.IN ( n218 ) , .QN ( n345 ) ) ;
AOINVX1 U377 (.IN ( n340 ) , .QN ( n342 ) ) ;
AOINVX1 U319 (.IN ( n228 ) , .QN ( n306 ) ) ;
AOINVX1 U355 (.IN ( n182 ) , .QN ( n295 ) ) ;
AOINVX1 U337 (.IN ( n259 ) , .QN ( n282 ) ) ;
AOINVX1 U82 (.IN ( n394 ) , .QN ( result_bits_data[9] ) ) ;
AOINVX1 U95 (.IN ( n391 ) , .QN ( result_bits_data[10] ) ) ;
AOINVX1 U53 (.IN ( n377 ) , .QN ( result_bits_data[5] ) ) ;
AOINVX1 U235 (.IN ( n181 ) , .QN ( n186 ) ) ;
AOINVX1 U2 (.IN ( n385 ) , .QN ( result_bits_data[7] ) ) ;
AOINVX1 U28 (.IN ( reset ) , .QN ( n355 ) ) ;
AODFFARX2 GCDdpath0_A_reg_reg_3_ (.CLK ( clk ) , .D ( n97 ) , .RSTB ( n355 ) 
    , .Q ( result_bits_data[3] ) , .QN ( n398 ) ) ;
AODFFARX2 GCDdpath0_B_reg_reg_11_ (.CLK ( clk ) , .D ( n105 ) , .RSTB ( n355 ) 
    , .Q ( GCDdpath0_B_reg[11] ) , .QN ( n383 ) ) ;
NAND2X1 U253 (.IN1 ( n314 ) , .QN ( n153 ) , .IN2 ( n155 ) ) ;
NOR2X1 U290 (.IN1 ( n180 ) , .QN ( n187 ) , .IN2 ( n179 ) ) ;
AOBUFX1 U177 (.IN ( n227 ) , .Q ( n308 ) ) ;
INVX1 U72 (.IN ( n189 ) , .QN ( n360 ) ) ;
NOR2X0 U98 (.QN ( n410 ) , .IN1 ( n362 ) , .IN2 ( n360 ) ) ;
INVX4 U76 (.IN ( n188 ) , .QN ( n362 ) ) ;
NOR2X2 U137 (.IN1 ( result_bits_data[1] ) , .IN2 ( n395 ) , .QN ( n274 ) ) ;
INVX2 U222 (.IN ( n392 ) , .QN ( result_bits_data[1] ) ) ;
INVX0 U77 (.QN ( result_bits_data[4] ) , .IN ( n55 ) ) ;
NOR2X0 U249 (.QN ( n155 ) , .IN1 ( n198 ) , .IN2 ( n195 ) ) ;
NAND2X1 U124 (.IN2 ( n361 ) , .IN1 ( n254 ) , .QN ( n258 ) ) ;
INVX0 U78 (.QN ( n58 ) , .IN ( n398 ) ) ;
NAND2X1 U133 (.IN1 ( n297 ) , .IN2 ( n183 ) , .QN ( n149 ) ) ;
NAND2X2 U148 (.IN1 ( n144 ) , .QN ( n182 ) , .IN2 ( n143 ) ) ;
NOR2X0 U268 (.QN ( n217 ) , .IN1 ( n47 ) , .IN2 ( n159 ) ) ;
NAND2X0 U81 (.IN1 ( n258 ) , .QN ( n85 ) , .IN2 ( n150 ) ) ;
NAND2X0 U97 (.IN1 ( n149 ) , .IN2 ( n148 ) , .QN ( n409 ) ) ;
OR3X1 U94 (.IN2 ( n405 ) , .IN3 ( n406 ) , .Q ( n117 ) , .IN1 ( n404 ) ) ;
AND2X1 U93 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[15] ) , .Q ( n406 ) ) ;
AND2X1 U92 (.IN1 ( n362 ) , .IN2 ( result_bits_data[15] ) , .Q ( n405 ) ) ;
AND2X1 U91 (.IN1 ( GCDdpath0_B_reg[15] ) , .IN2 ( n72 ) , .Q ( n404 ) ) ;
OR3X1 U90 (.IN2 ( n402 ) , .IN3 ( n403 ) , .Q ( n108 ) , .IN1 ( n401 ) ) ;
AND2X1 U87 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[8] ) , .Q ( n403 ) ) ;
AND2X1 U86 (.IN1 ( n362 ) , .IN2 ( result_bits_data[8] ) , .Q ( n402 ) ) ;
AND2X1 U84 (.IN1 ( GCDdpath0_B_reg[8] ) , .IN2 ( n410 ) , .Q ( n401 ) ) ;
NOR2X0 U79 (.QN ( n393 ) , .IN1 ( n140 ) , .IN2 ( n273 ) ) ;
NOR2X0 U156 (.QN ( n169 ) , .IN1 ( n172 ) , .IN2 ( n340 ) ) ;
NOR2X2 U151 (.IN1 ( n140 ) , .IN2 ( n273 ) , .QN ( n262 ) ) ;
NOR2X0 U176 (.QN ( n230 ) , .IN1 ( n411 ) , .IN2 ( n382 ) ) ;
NOR2X0 U75 (.IN1 ( n362 ) , .QN ( n72 ) , .IN2 ( n360 ) ) ;
NOR2X2 U135 (.IN1 ( n58 ) , .IN2 ( n387 ) , .QN ( n285 ) ) ;
NAND2X2 U294 (.QN ( n188 ) , .IN2 ( n181 ) , .IN1 ( n187 ) ) ;
NAND2X0 U140 (.IN1 ( n234 ) , .IN2 ( n361 ) , .QN ( n238 ) ) ;
NOR2X0 U172 (.QN ( n147 ) , .IN1 ( n353 ) , .IN2 ( n384 ) ) ;
NOR2X2 U89 (.IN1 ( n362 ) , .QN ( n73 ) , .IN2 ( n360 ) ) ;
NOR2X2 U27 (.IN2 ( n360 ) , .QN ( n170 ) , .IN1 ( n362 ) ) ;
OR2X1 U144 (.IN2 ( n377 ) , .IN1 ( GCDdpath0_B_reg[5] ) , .Q ( n148 ) ) ;
OR2X1 U149 (.IN2 ( n376 ) , .IN1 ( result_bits_data[15] ) , .Q ( n156 ) ) ;
OR2X1 U209 (.IN2 ( n190 ) , .IN1 ( n187 ) , .Q ( n121 ) ) ;
NOR2X0 U134 (.QN ( n284 ) , .IN1 ( GCDdpath0_B_reg[3] ) , .IN2 ( n398 ) ) ;
AODFFARX2 GCDdpath0_A_reg_reg_15_ (.CLK ( clk ) , .D ( n116 ) , .RSTB ( n355 ) 
    , .Q ( result_bits_data[15] ) , .QN ( n381 ) ) ;
NOR2X2 U36 (.IN1 ( n262 ) , .QN ( n3 ) , .IN2 ( n260 ) ) ;
AOINVX2 U146 (.IN ( n146 ) , .QN ( n315 ) ) ;
NAND2X2 U244 (.IN1 ( n3 ) , .QN ( n144 ) , .IN2 ( n141 ) ) ;
NAND2X1 U85 (.IN1 ( n163 ) , .QN ( n87 ) , .IN2 ( n120 ) ) ;
NOR2X0 U174 (.QN ( n198 ) , .IN1 ( n250 ) , .IN2 ( n386 ) ) ;
NOR2X1 U248 (.QN ( n195 ) , .IN1 ( result_bits_data[6] ) , .IN2 ( n372 ) ) ;
NOR2X0 U247 (.QN ( n145 ) , .IN1 ( n147 ) , .IN2 ( n296 ) ) ;
NOR2X0 U266 (.QN ( n207 ) , .IN1 ( n230 ) , .IN2 ( n228 ) ) ;
NAND2X2 U147 (.IN1 ( n182 ) , .QN ( n146 ) , .IN2 ( n145 ) ) ;
NAND2X0 U127 (.IN1 ( n135 ) , .IN2 ( n134 ) , .QN ( n363 ) ) ;
NAND2X1 U307 (.IN1 ( n207 ) , .IN2 ( n227 ) , .QN ( n325 ) ) ;
NAND2X0 U125 (.IN1 ( operands_rdy ) , .IN2 ( operands_val ) , .QN ( n189 ) ) ;
NAND2X0 U126 (.IN1 ( n363 ) , .IN2 ( n181 ) , .QN ( n190 ) ) ;
NOR2X0 U88 (.IN2 ( n86 ) , .QN ( n334 ) , .IN1 ( n330 ) ) ;
AND2X1 U44 (.Q ( n11 ) , .IN1 ( n362 ) , .IN2 ( result_bits_data[14] ) ) ;
AND2X1 U3 (.Q ( n30 ) , .IN1 ( n362 ) , .IN2 ( result_bits_data[7] ) ) ;
NAND2X0 U80 (.IN1 ( n238 ) , .QN ( n91 ) , .IN2 ( n164 ) ) ;
AND3X1 U15 (.IN2 ( n236 ) , .IN1 ( n237 ) , .IN3 ( n235 ) , .Q ( n164 ) ) ;
OR2X1 U10 (.IN2 ( n121 ) , .IN1 ( n21 ) , .Q ( n163 ) ) ;
AND3X1 U8 (.IN2 ( n256 ) , .IN1 ( n257 ) , .IN3 ( n255 ) , .Q ( n150 ) ) ;
AND3X1 U7 (.IN2 ( n248 ) , .IN1 ( n249 ) , .IN3 ( n247 ) , .Q ( n120 ) ) ;
OR2X1 U6 (.IN2 ( n329 ) , .IN1 ( n328 ) , .Q ( n86 ) ) ;
AND2X1 U5 (.IN1 ( n190 ) , .IN2 ( n189 ) , .Q ( n84 ) ) ;
AND2X1 U4 (.IN1 ( n158 ) , .IN2 ( n209 ) , .Q ( n83 ) ) ;
OR2X1 U1 (.IN2 ( n379 ) , .IN1 ( GCDdpath0_B_reg[6] ) , .Q ( n82 ) ) ;
NAND2X0 U164 (.IN1 ( n222 ) , .IN2 ( n361 ) , .QN ( n226 ) ) ;
NAND2X0 U163 (.IN1 ( n335 ) , .IN2 ( n361 ) , .QN ( n339 ) ) ;
NAND2X1 U313 (.IN1 ( n227 ) , .IN2 ( n217 ) , .QN ( n343 ) ) ;
NAND3X0 U74 (.QN ( n112 ) , .IN3 ( n52 ) , .IN2 ( n51 ) , .IN1 ( n50 ) ) ;
AND2X1 U70 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[6] ) , .Q ( n43 ) ) ;
AND2X1 U69 (.IN1 ( GCDdpath0_B_reg[6] ) , .IN2 ( n170 ) , .Q ( n41 ) ) ;
AND2X1 U68 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[9] ) , .Q ( n40 ) ) ;
AND2X1 U67 (.IN1 ( GCDdpath0_B_reg[9] ) , .IN2 ( n170 ) , .Q ( n38 ) ) ;
NAND3X0 U66 (.QN ( n113 ) , .IN3 ( n37 ) , .IN2 ( n36 ) , .IN1 ( n35 ) ) ;
AND2X1 U65 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[5] ) , .Q ( n34 ) ) ;
AND2X1 U64 (.IN1 ( GCDdpath0_B_reg[5] ) , .IN2 ( n170 ) , .Q ( n32 ) ) ;
AND2X1 U63 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[7] ) , .Q ( n31 ) ) ;
AND2X1 U62 (.IN1 ( GCDdpath0_B_reg[7] ) , .IN2 ( n170 ) , .Q ( n29 ) ) ;
OR3X1 U61 (.IN2 ( n26 ) , .IN3 ( n27 ) , .Q ( n103 ) , .IN1 ( n25 ) ) ;
AND2X1 U60 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[13] ) , .Q ( n27 ) ) ;
AND2X1 U59 (.IN1 ( GCDdpath0_B_reg[13] ) , .IN2 ( n73 ) , .Q ( n25 ) ) ;
OR3X1 U58 (.IN2 ( n23 ) , .IN3 ( n24 ) , .Q ( n101 ) , .IN1 ( n22 ) ) ;
AND2X1 U57 (.IN1 ( result_bits_data[0] ) , .IN2 ( n362 ) , .Q ( n24 ) ) ;
AND2X1 U56 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[0] ) , .Q ( n23 ) ) ;
AND2X1 U55 (.IN1 ( GCDdpath0_B_reg[0] ) , .IN2 ( n73 ) , .Q ( n22 ) ) ;
XOR2X1 U54 (.IN2 ( n244 ) , .Q ( n21 ) , .IN1 ( n245 ) ) ;
OR3X1 U52 (.IN2 ( n17 ) , .IN3 ( n18 ) , .Q ( n114 ) , .IN1 ( n16 ) ) ;
AND2X1 U51 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[2] ) , .Q ( n18 ) ) ;
AND2X1 U50 (.IN1 ( GCDdpath0_B_reg[2] ) , .IN2 ( n73 ) , .Q ( n16 ) ) ;
OR3X1 U49 (.IN2 ( n14 ) , .IN3 ( n15 ) , .Q ( n105 ) , .IN1 ( n13 ) ) ;
AND2X1 U48 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[11] ) , .Q ( n15 ) ) ;
AND2X1 U47 (.IN1 ( GCDdpath0_B_reg[11] ) , .IN2 ( n73 ) , .Q ( n13 ) ) ;
OR3X1 U46 (.IN2 ( n11 ) , .IN3 ( n12 ) , .Q ( n102 ) , .IN1 ( n10 ) ) ;
AND2X1 U45 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[14] ) , .Q ( n12 ) ) ;
AND2X1 U43 (.IN1 ( GCDdpath0_B_reg[14] ) , .IN2 ( n73 ) , .Q ( n10 ) ) ;
OR3X1 U42 (.IN2 ( n8 ) , .IN3 ( n9 ) , .Q ( n106 ) , .IN1 ( n7 ) ) ;
AND2X1 U41 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[10] ) , .Q ( n9 ) ) ;
AND2X1 U40 (.IN1 ( GCDdpath0_B_reg[10] ) , .IN2 ( n170 ) , .Q ( n7 ) ) ;
OR3X1 U39 (.IN2 ( n5 ) , .IN3 ( n6 ) , .Q ( n104 ) , .IN1 ( n4 ) ) ;
AND2X1 U38 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[12] ) , .Q ( n6 ) ) ;
AND2X1 U37 (.IN1 ( GCDdpath0_B_reg[12] ) , .IN2 ( n73 ) , .Q ( n4 ) ) ;
AO21X1 U35 (.IN2 ( n155 ) , .IN1 ( n315 ) , .IN3 ( n154 ) , .Q ( n2 ) ) ;
OR2X1 U34 (.IN2 ( n371 ) , .IN1 ( GCDdpath0_B_reg[12] ) , .Q ( n1 ) ) ;
AND2X1 U33 (.IN1 ( n362 ) , .IN2 ( result_bits_data[10] ) , .Q ( n8 ) ) ;
AND2X1 U32 (.IN1 ( n362 ) , .IN2 ( result_bits_data[12] ) , .Q ( n5 ) ) ;
AND2X1 U31 (.IN1 ( n362 ) , .IN2 ( result_bits_data[2] ) , .Q ( n17 ) ) ;
AND2X1 U30 (.IN1 ( n362 ) , .IN2 ( result_bits_data[11] ) , .Q ( n14 ) ) ;
AND2X1 U29 (.IN1 ( n362 ) , .IN2 ( result_bits_data[13] ) , .Q ( n26 ) ) ;
AND2X1 U26 (.IN1 ( n362 ) , .IN2 ( result_bits_data[5] ) , .Q ( n33 ) ) ;
OR3X1 U25 (.IN2 ( n30 ) , .IN3 ( n31 ) , .Q ( n109 ) , .IN1 ( n29 ) ) ;
NAND2X0 U24 (.IN1 ( n362 ) , .IN2 ( result_bits_data[3] ) , .QN ( n36 ) ) ;
NAND2X0 U23 (.IN1 ( GCDdpath0_B_reg[3] ) , .IN2 ( n170 ) , .QN ( n35 ) ) ;
OR3X1 U22 (.IN2 ( n33 ) , .IN3 ( n34 ) , .Q ( n111 ) , .IN1 ( n32 ) ) ;
OR3X1 U21 (.IN2 ( n39 ) , .IN3 ( n40 ) , .Q ( n107 ) , .IN1 ( n38 ) ) ;
AND2X1 U20 (.IN1 ( n362 ) , .IN2 ( result_bits_data[9] ) , .Q ( n39 ) ) ;
NAND2X0 U19 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[3] ) , .QN ( n37 ) ) ;
OR3X1 U18 (.IN2 ( n42 ) , .IN3 ( n43 ) , .Q ( n110 ) , .IN1 ( n41 ) ) ;
AND2X1 U17 (.IN1 ( n362 ) , .IN2 ( result_bits_data[6] ) , .Q ( n42 ) ) ;
AND2X1 U14 (.IN1 ( result_bits_data[14] ) , .IN2 ( n189 ) , .Q ( n48 ) ) ;
NAND2X0 U13 (.IN1 ( GCDdpath0_B_reg[4] ) , .IN2 ( n73 ) , .QN ( n50 ) ) ;
NAND2X0 U12 (.IN1 ( n360 ) , .IN2 ( operands_bits_B[4] ) , .QN ( n52 ) ) ;
NAND2X0 U11 (.IN1 ( n362 ) , .IN2 ( result_bits_data[4] ) , .QN ( n51 ) ) ;
NAND2X2 U258 (.IN2 ( n152 ) , .IN1 ( n153 ) , .QN ( n154 ) ) ;
NOR2X0 U256 (.QN ( n151 ) , .IN1 ( n82 ) , .IN2 ( n198 ) ) ;
NAND2X1 U131 (.IN1 ( n165 ) , .IN2 ( n83 ) , .QN ( n168 ) ) ;
NOR2X0 U277 (.QN ( n166 ) , .IN1 ( n208 ) , .IN2 ( n331 ) ) ;
NOR2X0 U275 (.QN ( n329 ) , .IN1 ( GCDdpath0_B_reg[10] ) , .IN2 ( n391 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_1_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n395 ) 
    , .Q ( GCDdpath0_B_reg[1] ) , .D ( n115 ) ) ;
NOR2X0 U242 (.IN2 ( n260 ) , .QN ( n283 ) , .IN1 ( n393 ) ) ;
NOR2X2 U241 (.IN1 ( n75 ) , .IN2 ( n390 ) , .QN ( n260 ) ) ;
NAND2X1 U129 (.IN1 ( n218 ) , .IN2 ( n169 ) , .QN ( n178 ) ) ;
NAND2X2 U130 (.IN2 ( n167 ) , .IN1 ( n168 ) , .QN ( n218 ) ) ;
NOR2X2 U154 (.QN ( n273 ) , .IN1 ( n139 ) , .IN2 ( n392 ) ) ;
DFFARX2 GCDdpath0_A_reg_reg_1_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n392 ) 
    , .D ( n99 ) ) ;
NOR2X2 U152 (.IN1 ( n138 ) , .IN2 ( n397 ) , .QN ( n275 ) ) ;
NOR2X2 U136 (.QN ( n140 ) , .IN1 ( n274 ) , .IN2 ( n275 ) ) ;
OA21X1 U332 (.IN2 ( n343 ) , .IN3 ( n251 ) , .IN1 ( n340 ) , .Q ( n253 ) ) ;
AOINVX2 U150 (.IN ( n2 ) , .QN ( n161 ) ) ;
OR2X1 U373 (.IN2 ( n331 ) , .IN1 ( n332 ) , .Q ( n333 ) ) ;
NAND2X0 U315 (.IN1 ( n219 ) , .IN2 ( n1 ) , .QN ( n220 ) ) ;
XNOR2X1 U316 (.IN1 ( n221 ) , .IN2 ( n220 ) , .Q ( n222 ) ) ;
NAND2X0 U317 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[12] ) , .QN ( n225 ) ) ;
NAND4X0 U318 (.IN1 ( n226 ) , .QN ( n88 ) , .IN2 ( n225 ) , .IN3 ( n224 ) 
    , .IN4 ( n223 ) ) ;
AO21X1 U320 (.IN2 ( n306 ) , .IN1 ( n308 ) , .IN3 ( n229 ) , .Q ( n233 ) ) ;
NOR2X0 U321 (.QN ( n232 ) , .IN1 ( n231 ) , .IN2 ( n230 ) ) ;
XOR2X1 U322 (.IN2 ( n232 ) , .Q ( n234 ) , .IN1 ( n233 ) ) ;
NAND2X0 U323 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[9] ) , .QN ( n237 ) ) ;
OA21X1 U325 (.IN2 ( n345 ) , .IN3 ( n1 ) , .IN1 ( n241 ) , .Q ( n240 ) ) ;
OA21X1 U326 (.IN2 ( n343 ) , .IN3 ( n240 ) , .IN1 ( n241 ) , .Q ( n245 ) ) ;
NOR2X0 U327 (.QN ( n244 ) , .IN1 ( n243 ) , .IN2 ( n242 ) ) ;
NAND2X0 U329 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[13] ) , .QN ( n249 ) ) ;
OA21X1 U331 (.IN2 ( n345 ) , .IN3 ( n347 ) , .IN1 ( n340 ) , .Q ( n251 ) ) ;
NOR2X0 U333 (.QN ( n252 ) , .IN1 ( n346 ) , .IN2 ( n350 ) ) ;
XNOR2X1 U334 (.IN1 ( n253 ) , .IN2 ( n252 ) , .Q ( n254 ) ) ;
NAND2X0 U335 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[14] ) , .QN ( n257 ) ) ;
NOR2X0 U338 (.QN ( n261 ) , .IN1 ( n260 ) , .IN2 ( n282 ) ) ;
XNOR2X1 U339 (.IN1 ( n393 ) , .IN2 ( n261 ) , .Q ( n263 ) ) ;
NAND2X0 U340 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[2] ) , .QN ( n266 ) ) ;
NAND4X0 U341 (.IN1 ( n267 ) , .QN ( n98 ) , .IN2 ( n266 ) , .IN3 ( n265 ) 
    , .IN4 ( n264 ) ) ;
XOR2X1 U342 (.IN2 ( GCDdpath0_B_reg[0] ) , .Q ( n268 ) 
    , .IN1 ( result_bits_data[0] ) ) ;
NAND2X0 U343 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[0] ) , .QN ( n271 ) ) ;
NAND4X0 U344 (.IN1 ( n272 ) , .QN ( n100 ) , .IN2 ( n271 ) , .IN3 ( n270 ) 
    , .IN4 ( n269 ) ) ;
NOR2X0 U345 (.QN ( n276 ) , .IN1 ( n274 ) , .IN2 ( n273 ) ) ;
XNOR2X1 U346 (.IN1 ( n276 ) , .IN2 ( n275 ) , .Q ( n277 ) ) ;
NAND2X0 U347 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[1] ) , .QN ( n280 ) ) ;
NAND2X0 U348 (.IN1 ( n84 ) , .IN2 ( result_bits_data[1] ) , .QN ( n278 ) ) ;
NAND4X0 U349 (.IN1 ( n281 ) , .QN ( n99 ) , .IN2 ( n280 ) , .IN3 ( n279 ) 
    , .IN4 ( n278 ) ) ;
NOR2X0 U350 (.QN ( n287 ) , .IN1 ( n283 ) , .IN2 ( n282 ) ) ;
NOR2X0 U351 (.QN ( n286 ) , .IN1 ( n284 ) , .IN2 ( n285 ) ) ;
XNOR2X1 U352 (.IN1 ( n287 ) , .IN2 ( n286 ) , .Q ( n288 ) ) ;
NAND2X0 U353 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[3] ) , .QN ( n291 ) ) ;
NAND4X0 U354 (.IN1 ( n292 ) , .QN ( n97 ) , .IN2 ( n291 ) , .IN3 ( n290 ) 
    , .IN4 ( n289 ) ) ;
OA21X1 U356 (.IN2 ( n295 ) , .IN3 ( n294 ) , .IN1 ( n296 ) , .Q ( n299 ) ) ;
NAND2X0 U357 (.IN1 ( n148 ) , .IN2 ( n297 ) , .QN ( n298 ) ) ;
XOR2X1 U358 (.IN2 ( n298 ) , .Q ( n300 ) , .IN1 ( n299 ) ) ;
NAND2X0 U359 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[5] ) , .QN ( n303 ) ) ;
NAND4X0 U360 (.IN1 ( n304 ) , .QN ( n95 ) , .IN2 ( n303 ) , .IN3 ( n302 ) 
    , .IN4 ( n301 ) ) ;
NAND2X0 U361 (.IN1 ( n306 ) , .IN2 ( n305 ) , .QN ( n307 ) ) ;
XNOR2X1 U362 (.IN1 ( n308 ) , .IN2 ( n307 ) , .Q ( n309 ) ) ;
NAND2X0 U363 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[8] ) , .QN ( n312 ) ) ;
NAND4X0 U364 (.IN1 ( n313 ) , .QN ( n92 ) , .IN2 ( n312 ) , .IN3 ( n311 ) 
    , .IN4 ( n310 ) ) ;
NOR2X0 U365 (.QN ( n319 ) , .IN1 ( n315 ) , .IN2 ( n409 ) ) ;
NAND2X0 U366 (.IN1 ( n317 ) , .IN2 ( n82 ) , .QN ( n318 ) ) ;
XOR2X1 U367 (.IN2 ( n318 ) , .Q ( n320 ) , .IN1 ( n319 ) ) ;
NAND2X0 U368 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[6] ) , .QN ( n323 ) ) ;
NAND4X0 U369 (.IN1 ( n324 ) , .QN ( n94 ) , .IN2 ( n323 ) , .IN3 ( n322 ) 
    , .IN4 ( n321 ) ) ;
NOR2X0 U371 (.QN ( n328 ) , .IN1 ( n412 ) , .IN2 ( n326 ) ) ;
XOR2X1 U374 (.IN2 ( n333 ) , .Q ( n335 ) , .IN1 ( n334 ) ) ;
NAND2X0 U375 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[11] ) , .QN ( n338 ) ) ;
NAND4X0 U376 (.IN1 ( n339 ) , .QN ( n89 ) , .IN2 ( n338 ) , .IN3 ( n337 ) 
    , .IN4 ( n336 ) ) ;
NAND2X0 U378 (.IN1 ( n342 ) , .IN2 ( n341 ) , .QN ( n344 ) ) ;
NOR2X0 U379 (.QN ( n351 ) , .IN1 ( n343 ) , .IN2 ( n344 ) ) ;
NOR2X0 U380 (.QN ( n349 ) , .IN1 ( n345 ) , .IN2 ( n344 ) ) ;
NOR2X0 U381 (.QN ( n348 ) , .IN1 ( n347 ) , .IN2 ( n346 ) ) ;
OR4X1 U382 (.IN4 ( n348 ) , .IN2 ( n350 ) , .Q ( n354 ) , .IN1 ( n351 ) 
    , .IN3 ( n349 ) ) ;
NAND3X0 U383 (.QN ( n359 ) , .IN3 ( n352 ) , .IN2 ( n361 ) , .IN1 ( n354 ) ) ;
NAND2X0 U384 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[15] ) , .QN ( n358 ) ) ;
NAND4X0 U385 (.IN1 ( n359 ) , .QN ( n116 ) , .IN2 ( n358 ) , .IN3 ( n357 ) 
    , .IN4 ( n356 ) ) ;
ISOLANDX1 U403 (.ISO ( GCDctrl0_state[0] ) , .D ( n363 ) , .Q ( n364 ) ) ;
OA22X1 U404 (.IN2 ( n367 ) , .IN4 ( n364 ) , .IN1 ( result_rdy ) 
    , .IN3 ( GCDctrl0_state[1] ) , .Q ( n365 ) ) ;
NOR2X0 U405 (.QN ( n118 ) , .IN1 ( n365 ) , .IN2 ( reset ) ) ;
NAND2X0 U220 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[3] ) , .QN ( n290 ) ) ;
NAND2X0 U221 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[15] ) , .QN ( n357 ) ) ;
NOR2X0 U224 (.QN ( result_val ) , .IN1 ( n367 ) , .IN2 ( n366 ) ) ;
NOR2X0 U225 (.QN ( n123 ) , .IN1 ( GCDdpath0_B_reg[15] ) 
    , .IN2 ( GCDdpath0_B_reg[13] ) ) ;
NOR2X0 U226 (.QN ( n122 ) , .IN1 ( GCDdpath0_B_reg[11] ) 
    , .IN2 ( GCDdpath0_B_reg[9] ) ) ;
NOR2X0 U227 (.QN ( n125 ) , .IN1 ( GCDdpath0_B_reg[5] ) 
    , .IN2 ( GCDdpath0_B_reg[7] ) ) ;
NOR2X0 U228 (.QN ( n124 ) , .IN1 ( GCDdpath0_B_reg[3] ) 
    , .IN2 ( GCDdpath0_B_reg[1] ) ) ;
NOR2X0 U229 (.QN ( n135 ) , .IN1 ( n127 ) , .IN2 ( n126 ) ) ;
NOR2X0 U230 (.QN ( n129 ) , .IN1 ( GCDdpath0_B_reg[4] ) 
    , .IN2 ( GCDdpath0_B_reg[6] ) ) ;
NOR2X0 U231 (.QN ( n128 ) , .IN1 ( GCDdpath0_B_reg[2] ) 
    , .IN2 ( GCDdpath0_B_reg[14] ) ) ;
NOR2X0 U232 (.QN ( n131 ) , .IN1 ( GCDdpath0_B_reg[10] ) 
    , .IN2 ( GCDdpath0_B_reg[8] ) ) ;
NOR2X0 U233 (.QN ( n130 ) , .IN1 ( GCDdpath0_B_reg[12] ) 
    , .IN2 ( GCDdpath0_B_reg[0] ) ) ;
NOR2X0 U234 (.QN ( n134 ) , .IN1 ( n133 ) , .IN2 ( n132 ) ) ;
NOR2X0 U236 (.QN ( n137 ) , .IN1 ( n363 ) , .IN2 ( n186 ) ) ;
NOR2X0 U237 (.QN ( n136 ) , .IN1 ( n366 ) , .IN2 ( operands_val ) ) ;
OR4X1 U238 (.IN4 ( n136 ) , .IN2 ( reset ) , .Q ( n119 ) , .IN1 ( n137 ) 
    , .IN3 ( result_val ) ) ;
NOR2X0 U257 (.QN ( n199 ) , .IN1 ( GCDdpath0_B_reg[7] ) , .IN2 ( n385 ) ) ;
AO21X1 U259 (.IN2 ( n155 ) , .IN1 ( n315 ) , .IN3 ( n154 ) , .Q ( n227 ) ) ;
NOR2X0 U272 (.QN ( n231 ) , .IN1 ( GCDdpath0_B_reg[9] ) , .IN2 ( n394 ) ) ;
NOR2X0 U278 (.QN ( n332 ) , .IN1 ( GCDdpath0_B_reg[11] ) , .IN2 ( n370 ) ) ;
NOR2X0 U279 (.QN ( n167 ) , .IN1 ( n166 ) , .IN2 ( n332 ) ) ;
NOR2X0 U282 (.QN ( n171 ) , .IN1 ( n1 ) , .IN2 ( n242 ) ) ;
NOR2X0 U283 (.QN ( n243 ) , .IN1 ( GCDdpath0_B_reg[13] ) , .IN2 ( n378 ) ) ;
NOR2X0 U284 (.QN ( n347 ) , .IN1 ( n171 ) , .IN2 ( n243 ) ) ;
NOR2X0 U285 (.QN ( n176 ) , .IN1 ( n347 ) , .IN2 ( n172 ) ) ;
NOR2X0 U286 (.QN ( n350 ) , .IN1 ( GCDdpath0_B_reg[14] ) , .IN2 ( n380 ) ) ;
NOR2X0 U287 (.QN ( n352 ) , .IN1 ( GCDdpath0_B_reg[15] ) , .IN2 ( n381 ) ) ;
NOR2X0 U292 (.QN ( n184 ) , .IN1 ( n296 ) , .IN2 ( n183 ) ) ;
XOR2X1 U293 (.IN2 ( n184 ) , .Q ( n185 ) , .IN1 ( n182 ) ) ;
NAND2X0 U296 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[4] ) , .QN ( n193 ) ) ;
NAND4X0 U298 (.IN1 ( n194 ) , .QN ( n96 ) , .IN2 ( n193 ) , .IN3 ( n192 ) 
    , .IN4 ( n191 ) ) ;
NAND2X0 U300 (.IN1 ( n315 ) , .IN2 ( n317 ) , .QN ( n197 ) ) ;
NAND2X0 U301 (.IN1 ( n409 ) , .IN2 ( n317 ) , .QN ( n196 ) ) ;
NAND3X0 U302 (.QN ( n201 ) , .IN3 ( n196 ) , .IN2 ( n82 ) , .IN1 ( n197 ) ) ;
NOR2X0 U303 (.QN ( n200 ) , .IN1 ( n199 ) , .IN2 ( n198 ) ) ;
XOR2X1 U304 (.IN2 ( n200 ) , .Q ( n202 ) , .IN1 ( n201 ) ) ;
NAND2X0 U305 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[7] ) , .QN ( n205 ) ) ;
NAND4X0 U306 (.IN1 ( n206 ) , .QN ( n93 ) , .IN2 ( n205 ) , .IN3 ( n204 ) 
    , .IN4 ( n203 ) ) ;
NAND2X0 U308 (.IN1 ( n325 ) , .IN2 ( n412 ) , .QN ( n211 ) ) ;
NAND2X0 U309 (.IN1 ( n209 ) , .IN2 ( n208 ) , .QN ( n210 ) ) ;
XNOR2X1 U310 (.IN1 ( n211 ) , .IN2 ( n210 ) , .Q ( n212 ) ) ;
NAND2X0 U311 (.IN1 ( n362 ) , .IN2 ( GCDdpath0_B_reg[10] ) , .QN ( n215 ) ) ;
NAND4X0 U312 (.IN1 ( n216 ) , .QN ( n90 ) , .IN2 ( n215 ) , .IN3 ( n214 ) 
    , .IN4 ( n213 ) ) ;
NOR2X0 U128 (.QN ( n181 ) , .IN1 ( GCDctrl0_state[0] ) 
    , .IN2 ( GCDctrl0_state[1] ) ) ;
NAND2X0 U138 (.IN1 ( n156 ) , .IN2 ( n341 ) , .QN ( n172 ) ) ;
NOR2X0 U142 (.QN ( operands_rdy ) , .IN1 ( GCDctrl0_state[0] ) , .IN2 ( n366 ) ) ;
NAND2X1 U153 (.IN2 ( n74 ) , .IN1 ( n396 ) , .QN ( n294 ) ) ;
NOR2X0 U155 (.QN ( n241 ) , .IN1 ( result_bits_data[12] ) , .IN2 ( n375 ) ) ;
NOR2X0 U157 (.QN ( n242 ) , .IN1 ( result_bits_data[13] ) , .IN2 ( n374 ) ) ;
NAND2X0 U158 (.IN1 ( n131 ) , .IN2 ( n130 ) , .QN ( n132 ) ) ;
NAND2X0 U159 (.IN1 ( n129 ) , .IN2 ( n128 ) , .QN ( n133 ) ) ;
NAND2X0 U160 (.IN1 ( n125 ) , .IN2 ( n124 ) , .QN ( n126 ) ) ;
NAND2X0 U161 (.IN1 ( n202 ) , .IN2 ( n361 ) , .QN ( n206 ) ) ;
NAND2X0 U162 (.IN1 ( n320 ) , .IN2 ( n361 ) , .QN ( n324 ) ) ;
NAND2X0 U165 (.IN1 ( n300 ) , .IN2 ( n361 ) , .QN ( n304 ) ) ;
NAND2X0 U166 (.IN1 ( n361 ) , .IN2 ( n185 ) , .QN ( n194 ) ) ;
NAND2X0 U167 (.IN1 ( n361 ) , .IN2 ( n288 ) , .QN ( n292 ) ) ;
NAND2X0 U168 (.IN1 ( n361 ) , .IN2 ( n263 ) , .QN ( n267 ) ) ;
NAND2X0 U169 (.IN1 ( n361 ) , .IN2 ( n268 ) , .QN ( n272 ) ) ;
NAND2X0 U173 (.IN1 ( n174 ) , .IN2 ( n173 ) , .QN ( n175 ) ) ;
NOR2X0 U178 (.QN ( n296 ) , .IN1 ( result_bits_data[4] ) , .IN2 ( n396 ) ) ;
NOR2X0 U179 (.QN ( n346 ) , .IN1 ( result_bits_data[14] ) , .IN2 ( n373 ) ) ;
NAND2X0 U180 (.IN1 ( n361 ) , .IN2 ( n277 ) , .QN ( n281 ) ) ;
NAND2X0 U181 (.IN1 ( n123 ) , .IN2 ( n122 ) , .QN ( n127 ) ) ;
NAND2X0 U182 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[7] ) , .QN ( n204 ) ) ;
NAND2X0 U183 (.IN1 ( n84 ) , .IN2 ( result_bits_data[7] ) , .QN ( n203 ) ) ;
NAND2X0 U184 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[10] ) , .QN ( n214 ) ) ;
NAND2X0 U185 (.IN1 ( n84 ) , .IN2 ( result_bits_data[10] ) , .QN ( n213 ) ) ;
NAND2X0 U186 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[6] ) , .QN ( n322 ) ) ;
NAND2X0 U187 (.IN1 ( n84 ) , .IN2 ( result_bits_data[6] ) , .QN ( n321 ) ) ;
NAND2X0 U188 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[11] ) , .QN ( n337 ) ) ;
NAND2X0 U189 (.IN1 ( n84 ) , .IN2 ( result_bits_data[11] ) , .QN ( n336 ) ) ;
NAND2X0 U190 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[9] ) , .QN ( n236 ) ) ;
NAND2X0 U191 (.IN1 ( n84 ) , .IN2 ( result_bits_data[9] ) , .QN ( n235 ) ) ;
NAND2X0 U192 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[13] ) , .QN ( n248 ) ) ;
NAND2X0 U193 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[12] ) , .QN ( n224 ) ) ;
NAND2X0 U194 (.IN1 ( n84 ) , .IN2 ( result_bits_data[12] ) , .QN ( n223 ) ) ;
NAND2X0 U195 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[8] ) , .QN ( n311 ) ) ;
NAND2X0 U196 (.IN1 ( n84 ) , .IN2 ( result_bits_data[8] ) , .QN ( n310 ) ) ;
NAND2X0 U197 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[5] ) , .QN ( n302 ) ) ;
NAND2X0 U198 (.IN1 ( n84 ) , .IN2 ( result_bits_data[5] ) , .QN ( n301 ) ) ;
NAND2X0 U199 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[4] ) , .QN ( n192 ) ) ;
NAND2X0 U200 (.IN1 ( n84 ) , .IN2 ( result_bits_data[4] ) , .QN ( n191 ) ) ;
NAND2X0 U201 (.IN1 ( n84 ) , .IN2 ( result_bits_data[3] ) , .QN ( n289 ) ) ;
NAND2X0 U202 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[2] ) , .QN ( n265 ) ) ;
NAND2X0 U203 (.IN1 ( n84 ) , .IN2 ( result_bits_data[2] ) , .QN ( n264 ) ) ;
NAND2X0 U204 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[0] ) , .QN ( n270 ) ) ;
NAND2X0 U205 (.IN1 ( n84 ) , .IN2 ( result_bits_data[0] ) , .QN ( n269 ) ) ;
NAND2X0 U206 (.IN1 ( n84 ) , .IN2 ( result_bits_data[15] ) , .QN ( n356 ) ) ;
NAND2X0 U207 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[14] ) , .QN ( n256 ) ) ;
NAND2X0 U208 (.IN1 ( n48 ) , .IN2 ( n190 ) , .QN ( n255 ) ) ;
NAND2X0 U210 (.IN1 ( n156 ) , .IN2 ( n350 ) , .QN ( n174 ) ) ;
NOR2X0 U211 (.QN ( n152 ) , .IN1 ( n151 ) , .IN2 ( n199 ) ) ;
NOR2X0 U213 (.QN ( n177 ) , .IN1 ( n176 ) , .IN2 ( n175 ) ) ;
NAND2X0 U215 (.IN1 ( n345 ) , .IN2 ( n343 ) , .QN ( n221 ) ) ;
NAND2X0 U216 (.IN1 ( n360 ) , .IN2 ( operands_bits_A[1] ) , .QN ( n279 ) ) ;
NAND2X0 U217 (.IN1 ( n212 ) , .IN2 ( n361 ) , .QN ( n216 ) ) ;
NAND2X0 U218 (.IN1 ( n84 ) , .IN2 ( result_bits_data[13] ) , .QN ( n247 ) ) ;
NAND2X0 U219 (.IN1 ( n309 ) , .IN2 ( n361 ) , .QN ( n313 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_0_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n388 ) 
    , .Q ( result_bits_data[0] ) , .D ( n100 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_2_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n61 ) 
    , .Q ( n75 ) , .D ( n98 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_4_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n55 ) 
    , .Q ( n74 ) , .D ( n96 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_5_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n377 ) 
    , .Q ( n353 ) , .D ( n95 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_8_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n369 ) 
    , .Q ( result_bits_data[8] ) , .D ( n92 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_9_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n382 ) 
    , .Q ( GCDdpath0_B_reg[9] ) , .D ( n107 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_6_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n379 ) 
    , .Q ( result_bits_data[6] ) , .D ( n94 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_10_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n391 ) 
    , .Q ( n76 ) , .D ( n90 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_7_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n385 ) 
    , .Q ( n250 ) , .D ( n93 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_15_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n376 ) 
    , .Q ( GCDdpath0_B_reg[15] ) , .D ( n117 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_5_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n384 ) 
    , .Q ( GCDdpath0_B_reg[5] ) , .D ( n111 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_4_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n396 ) 
    , .Q ( GCDdpath0_B_reg[4] ) , .D ( n112 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_14_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n380 ) 
    , .Q ( result_bits_data[14] ) , .D ( n85 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_12_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n371 ) 
    , .Q ( result_bits_data[12] ) , .D ( n88 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_13_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n378 ) 
    , .Q ( result_bits_data[13] ) , .D ( n87 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_9_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n394 ) 
    , .Q ( n411 ) , .D ( n91 ) ) ;
DFFARX1 GCDdpath0_A_reg_reg_11_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n370 ) 
    , .Q ( result_bits_data[11] ) , .D ( n89 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_0_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n397 ) 
    , .Q ( GCDdpath0_B_reg[0] ) , .D ( n101 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_8_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n368 ) 
    , .Q ( GCDdpath0_B_reg[8] ) , .D ( n108 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_3_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n387 ) 
    , .Q ( GCDdpath0_B_reg[3] ) , .D ( n113 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_2_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n390 ) 
    , .Q ( GCDdpath0_B_reg[2] ) , .D ( n114 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_6_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n372 ) 
    , .Q ( GCDdpath0_B_reg[6] ) , .D ( n110 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_10_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n389 ) 
    , .Q ( GCDdpath0_B_reg[10] ) , .D ( n106 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_12_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n375 ) 
    , .Q ( GCDdpath0_B_reg[12] ) , .D ( n104 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_7_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n386 ) 
    , .Q ( GCDdpath0_B_reg[7] ) , .D ( n109 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_14_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n373 ) 
    , .Q ( GCDdpath0_B_reg[14] ) , .D ( n102 ) ) ;
DFFARX1 GCDdpath0_B_reg_reg_13_ (.CLK ( clk ) , .RSTB ( n355 ) , .QN ( n374 ) 
    , .Q ( GCDdpath0_B_reg[13] ) , .D ( n103 ) ) ;
SHFILL2 xofiller_SHFILL2_1 () ;
SHFILL2 xofiller_SHFILL2_2 () ;
SHFILL2 xofiller_SHFILL2_3 () ;
SHFILL2 xofiller_SHFILL2_4 () ;
SHFILL2 xofiller_SHFILL2_5 () ;
SHFILL2 xofiller_SHFILL2_6 () ;
SHFILL2 xofiller_SHFILL2_7 () ;
SHFILL2 xofiller_SHFILL2_8 () ;
SHFILL2 xofiller_SHFILL2_9 () ;
SHFILL2 xofiller_SHFILL2_10 () ;
SHFILL2 xofiller_SHFILL2_11 () ;
SHFILL2 xofiller_SHFILL2_12 () ;
SHFILL2 xofiller_SHFILL2_13 () ;
SHFILL2 xofiller_SHFILL2_14 () ;
SHFILL2 xofiller_SHFILL2_15 () ;
SHFILL2 xofiller_SHFILL2_16 () ;
SHFILL2 xofiller_SHFILL2_17 () ;
SHFILL2 xofiller_SHFILL2_18 () ;
SHFILL2 xofiller_SHFILL2_19 () ;
SHFILL2 xofiller_SHFILL2_20 () ;
SHFILL2 xofiller_SHFILL2_21 () ;
SHFILL2 xofiller_SHFILL2_22 () ;
SHFILL2 xofiller_SHFILL2_23 () ;
SHFILL2 xofiller_SHFILL2_24 () ;
SHFILL2 xofiller_SHFILL2_25 () ;
SHFILL2 xofiller_SHFILL2_26 () ;
SHFILL2 xofiller_SHFILL2_27 () ;
SHFILL2 xofiller_SHFILL2_28 () ;
SHFILL2 xofiller_SHFILL2_29 () ;
SHFILL2 xofiller_SHFILL2_30 () ;
SHFILL2 xofiller_SHFILL2_31 () ;
SHFILL2 xofiller_SHFILL2_32 () ;
SHFILL2 xofiller_SHFILL2_33 () ;
SHFILL2 xofiller_SHFILL2_34 () ;
SHFILL2 xofiller_SHFILL2_35 () ;
SHFILL2 xofiller_SHFILL2_36 () ;
SHFILL2 xofiller_SHFILL2_37 () ;
SHFILL2 xofiller_SHFILL2_38 () ;
SHFILL2 xofiller_SHFILL2_39 () ;
SHFILL2 xofiller_SHFILL2_40 () ;
SHFILL2 xofiller_SHFILL2_41 () ;
SHFILL2 xofiller_SHFILL2_42 () ;
SHFILL2 xofiller_SHFILL2_43 () ;
SHFILL2 xofiller_SHFILL2_44 () ;
SHFILL2 xofiller_SHFILL2_45 () ;
SHFILL2 xofiller_SHFILL2_46 () ;
SHFILL2 xofiller_SHFILL2_47 () ;
SHFILL2 xofiller_SHFILL2_48 () ;
SHFILL2 xofiller_SHFILL2_49 () ;
SHFILL2 xofiller_SHFILL2_50 () ;
SHFILL2 xofiller_SHFILL2_51 () ;
SHFILL2 xofiller_SHFILL2_52 () ;
SHFILL2 xofiller_SHFILL2_53 () ;
SHFILL2 xofiller_SHFILL2_54 () ;
SHFILL2 xofiller_SHFILL2_55 () ;
SHFILL2 xofiller_SHFILL2_56 () ;
SHFILL2 xofiller_SHFILL2_57 () ;
SHFILL2 xofiller_SHFILL2_58 () ;
SHFILL2 xofiller_SHFILL2_59 () ;
SHFILL2 xofiller_SHFILL2_60 () ;
SHFILL2 xofiller_SHFILL2_61 () ;
SHFILL2 xofiller_SHFILL2_62 () ;
SHFILL2 xofiller_SHFILL2_63 () ;
SHFILL2 xofiller_SHFILL2_64 () ;
SHFILL2 xofiller_SHFILL2_65 () ;
SHFILL2 xofiller_SHFILL2_66 () ;
SHFILL2 xofiller_SHFILL2_67 () ;
SHFILL2 xofiller_SHFILL2_68 () ;
SHFILL2 xofiller_SHFILL2_69 () ;
SHFILL2 xofiller_SHFILL2_70 () ;
SHFILL2 xofiller_SHFILL2_71 () ;
SHFILL2 xofiller_SHFILL2_72 () ;
SHFILL2 xofiller_SHFILL2_73 () ;
SHFILL2 xofiller_SHFILL2_74 () ;
SHFILL2 xofiller_SHFILL2_75 () ;
SHFILL2 xofiller_SHFILL2_76 () ;
SHFILL2 xofiller_SHFILL2_77 () ;
SHFILL2 xofiller_SHFILL2_78 () ;
SHFILL2 xofiller_SHFILL2_79 () ;
SHFILL2 xofiller_SHFILL2_80 () ;
SHFILL2 xofiller_SHFILL2_81 () ;
SHFILL2 xofiller_SHFILL2_82 () ;
SHFILL2 xofiller_SHFILL2_83 () ;
SHFILL2 xofiller_SHFILL2_84 () ;
SHFILL2 xofiller_SHFILL2_85 () ;
SHFILL2 xofiller_SHFILL2_86 () ;
SHFILL2 xofiller_SHFILL2_87 () ;
SHFILL2 xofiller_SHFILL2_88 () ;
SHFILL2 xofiller_SHFILL2_89 () ;
SHFILL2 xofiller_SHFILL2_90 () ;
SHFILL2 xofiller_SHFILL2_91 () ;
SHFILL2 xofiller_SHFILL2_92 () ;
SHFILL2 xofiller_SHFILL2_93 () ;
SHFILL2 xofiller_SHFILL2_94 () ;
SHFILL2 xofiller_SHFILL2_95 () ;
SHFILL2 xofiller_SHFILL2_96 () ;
SHFILL2 xofiller_SHFILL2_97 () ;
SHFILL2 xofiller_SHFILL2_98 () ;
SHFILL2 xofiller_SHFILL2_99 () ;
SHFILL2 xofiller_SHFILL2_100 () ;
SHFILL2 xofiller_SHFILL2_101 () ;
SHFILL2 xofiller_SHFILL2_102 () ;
SHFILL2 xofiller_SHFILL2_103 () ;
SHFILL2 xofiller_SHFILL2_104 () ;
SHFILL2 xofiller_SHFILL2_105 () ;
SHFILL2 xofiller_SHFILL2_106 () ;
SHFILL2 xofiller_SHFILL2_107 () ;
SHFILL2 xofiller_SHFILL2_108 () ;
SHFILL2 xofiller_SHFILL2_109 () ;
SHFILL2 xofiller_SHFILL2_110 () ;
SHFILL2 xofiller_SHFILL2_111 () ;
SHFILL2 xofiller_SHFILL2_112 () ;
SHFILL2 xofiller_SHFILL2_113 () ;
SHFILL2 xofiller_SHFILL2_114 () ;
SHFILL2 xofiller_SHFILL2_115 () ;
SHFILL2 xofiller_SHFILL2_116 () ;
SHFILL2 xofiller_SHFILL2_117 () ;
SHFILL2 xofiller_SHFILL2_118 () ;
SHFILL2 xofiller_SHFILL2_119 () ;
SHFILL2 xofiller_SHFILL2_120 () ;
SHFILL2 xofiller_SHFILL2_121 () ;
SHFILL2 xofiller_SHFILL2_122 () ;
SHFILL2 xofiller_SHFILL2_123 () ;
SHFILL2 xofiller_SHFILL2_124 () ;
SHFILL2 xofiller_SHFILL2_125 () ;
SHFILL2 xofiller_SHFILL2_126 () ;
SHFILL2 xofiller_SHFILL2_127 () ;
SHFILL2 xofiller_SHFILL2_128 () ;
SHFILL2 xofiller_SHFILL2_129 () ;
SHFILL2 xofiller_SHFILL2_130 () ;
SHFILL2 xofiller_SHFILL2_131 () ;
SHFILL2 xofiller_SHFILL2_132 () ;
SHFILL2 xofiller_SHFILL2_133 () ;
SHFILL2 xofiller_SHFILL2_134 () ;
SHFILL2 xofiller_SHFILL2_135 () ;
SHFILL2 xofiller_SHFILL2_136 () ;
SHFILL2 xofiller_SHFILL2_137 () ;
SHFILL2 xofiller_SHFILL2_138 () ;
SHFILL2 xofiller_SHFILL2_139 () ;
SHFILL2 xofiller_SHFILL2_140 () ;
SHFILL2 xofiller_SHFILL2_141 () ;
SHFILL2 xofiller_SHFILL2_142 () ;
SHFILL2 xofiller_SHFILL2_143 () ;
SHFILL2 xofiller_SHFILL2_144 () ;
SHFILL2 xofiller_SHFILL2_145 () ;
SHFILL2 xofiller_SHFILL2_146 () ;
SHFILL2 xofiller_SHFILL2_147 () ;
SHFILL2 xofiller_SHFILL2_148 () ;
SHFILL2 xofiller_SHFILL2_149 () ;
SHFILL2 xofiller_SHFILL2_150 () ;
SHFILL2 xofiller_SHFILL2_151 () ;
SHFILL2 xofiller_SHFILL2_152 () ;
SHFILL2 xofiller_SHFILL2_153 () ;
endmodule


