ICV_HOME_DIR      = /usr/local/synopsys/icvalidator/K-2015.12-3
WORKING_DIR       = .
INLIB             = mylibrary
INLIB_PATH        = 
OUTLIB            = run_details/adder_1bit
OUTLIB_PATH       = .
BLOCK             = adder_1bit
PYDB_PATH         = run_details/pydb
RUN_DETAILS_DIR   = run_details
NDB_PATH          = run_details/.ndb
FORMAT            = OPENACCESS
EVACCESS_PATH     = run_details/pydb
SCHEMATIC_FORMAT  = ICV
GROUP_PATH        = run_details/group
RUNSET_FILE_NAME  = rules.drc.9m_saed90_icv.drc.rs
